// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xforward_kernel.h"

extern XForward_kernel_Config XForward_kernel_ConfigTable[];

XForward_kernel_Config *XForward_kernel_LookupConfig(u16 DeviceId) {
	XForward_kernel_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFORWARD_KERNEL_NUM_INSTANCES; Index++) {
		if (XForward_kernel_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XForward_kernel_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XForward_kernel_Initialize(XForward_kernel *InstancePtr, u16 DeviceId) {
	XForward_kernel_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XForward_kernel_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XForward_kernel_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

