-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity exp_generic_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of exp_generic_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv46_B17217F7D : STD_LOGIC_VECTOR (45 downto 0) := "0000000000101100010111001000010111111101111101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv28_4 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000100";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_382 : STD_LOGIC_VECTOR (9 downto 0) := "1110000010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_7F800000 : STD_LOGIC_VECTOR (31 downto 0) := "01111111100000000000000000000000";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv25_B8A : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000101110001010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 : STD_LOGIC;
    signal hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 : STD_LOGIC_VECTOR (26 downto 0);
    signal hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 : STD_LOGIC;
    signal hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_188_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter13_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter14_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter15_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter16_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter17_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter18_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter19_p_Result_s_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_demorgan_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter13_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter14_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter15_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter16_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter17_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter18_not_demorgan_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_i_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter13_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter14_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter15_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter16_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter17_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter18_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter19_tmp_4_i_i_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_8_fu_264_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_8_reg_928 : STD_LOGIC_VECTOR (24 downto 0);
    signal isNeg_fu_272_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_933 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_isNeg_reg_933 : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_assign_1_fu_290_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_1_reg_939 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_25_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter13_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter14_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter15_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter16_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter17_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter18_tmp_25_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter13_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter14_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter15_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter16_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter17_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter18_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter19_tmp_78_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_25_cast1_fu_319_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal p_Val2_25_cast1_reg_959 : STD_LOGIC_VECTOR (35 downto 0);
    signal sh_assign_1_cast_fu_323_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sh_assign_1_cast_reg_964 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_9_fu_349_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter2_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter3_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter4_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter5_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter6_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter7_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter8_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter9_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_reg_pp0_iter10_p_Val2_9_reg_970 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_1_reg_975 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_reg_981 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_72_reg_986 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_tmp_72_reg_986 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter13_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter14_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter15_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter16_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter17_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter18_tmp_26_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_893_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_reg_1001 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_74_fu_426_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_74_reg_1007 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_exp_V_3_fu_464_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter5_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter6_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter7_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter8_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter9_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter10_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter11_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter12_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter13_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter14_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter15_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter16_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_pp0_iter17_r_exp_V_3_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_48_reg_1024 : STD_LOGIC_VECTOR (35 downto 0);
    signal m_diff_hi_V_reg_1029 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_reg_pp0_iter12_m_diff_hi_V_reg_1029 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_15_fu_521_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_15_reg_1034 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_pp0_iter12_p_Val2_15_reg_1034 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_pp0_iter13_p_Val2_15_reg_1034 : STD_LOGIC_VECTOR (17 downto 0);
    signal Z2_ind_V_reg_1039 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Val2_16_reg_1054 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_17_reg_1059 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_reg_pp0_iter15_p_Val2_17_reg_1059 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_reg_pp0_iter16_p_Val2_17_reg_1059 : STD_LOGIC_VECTOR (26 downto 0);
    signal exp_Z1P_m_1_V_reg_1064 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_19_reg_1069 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_6_fu_584_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal p_Val2_6_reg_1084 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_902_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal p_Val2_1_reg_1089 : STD_LOGIC_VECTOR (35 downto 0);
    signal p_Val2_10_fu_600_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal p_Val2_10_reg_1094 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_76_fu_606_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_76_reg_1100 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_exp_V_2_fu_619_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_exp_V_2_reg_1105 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_77_reg_1110 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_79_fu_636_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_79_reg_1115 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp1_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_reg_1120 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_reg_1126 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp35_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp35_reg_1132 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_789_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_39_reg_1137 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_i1_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_17_fu_539_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Val2_s_fu_184_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal loc_V_fu_196_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal loc_V_1_fu_206_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_i_i_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_i_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_i_i_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_cast_fu_240_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_5_fu_250_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_7_fu_258_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal m_exp_fu_244_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_280_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_cast_fu_286_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_18_fu_312_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sh_assign_1_cast_cast_fu_326_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_5_fu_333_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_9_fu_329_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_5_cast_fu_339_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_6_fu_343_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_2_fu_384_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_388_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_47_fu_395_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_402_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_10_fu_415_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_429_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_2_fu_450_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_73_fu_438_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_456_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_475_p0 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_fu_475_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_16_fu_494_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal tmp_15_fu_491_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_21_cast_fu_501_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal p_Val2_5_fu_505_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_6_i_fu_543_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_7_i_fu_546_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_4_fu_549_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_20_fu_581_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_21_fu_590_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_28_cast_fu_597_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal r_exp_V_fu_614_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_660_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_30_fu_669_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal out_exp_V_fu_685_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal loc_V_2_fu_678_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal not_Result_i4_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp44_demorgan_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_754_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_690_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp2_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_fu_776_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_36_fu_772_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_is_ninf_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_i_not_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp32_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp33_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_853_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp34_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_867_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_893_p0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_902_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_902_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to19 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_902_p00 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_fu_902_p10 : STD_LOGIC_VECTOR (35 downto 0);

    component forward_kernel_mul_37ns_10s_46_6 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (36 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (45 downto 0) );
    end component;


    component forward_kernel_mac_muladd_13ns_13s_16s_25_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component forward_kernel_mul_mul_18ns_18ns_36_3 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component exp_generic_float_s_hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component exp_generic_float_s_hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U : component exp_generic_float_s_hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V
    generic map (
        DataWidth => 27,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0,
        ce0 => hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0,
        q0 => hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0);

    hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U : component exp_generic_float_s_hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V
    generic map (
        DataWidth => 8,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0,
        ce0 => hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0,
        q0 => hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0);

    forward_kernel_mul_37ns_10s_46_6_U1 : component forward_kernel_mul_37ns_10s_46_6
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 37,
        din1_WIDTH => 10,
        dout_WIDTH => 46)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_475_p0,
        din1 => r_exp_V_3_reg_1012,
        ce => ap_const_logic_1,
        dout => grp_fu_475_p2);

    forward_kernel_mac_muladd_13ns_13s_16s_25_2_U2 : component forward_kernel_mac_muladd_13ns_13s_16s_25_2
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 13,
        din1_WIDTH => 13,
        din2_WIDTH => 16,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_893_p0,
        din1 => tmp_7_reg_981,
        din2 => tmp_10_fu_415_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_893_p3);

    forward_kernel_mul_mul_18ns_18ns_36_3_U3 : component forward_kernel_mul_mul_18ns_18ns_36_3
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_902_p0,
        din1 => grp_fu_902_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_902_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_subdone = ap_const_boolean_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_block_pp0_stage0_11001 = ap_const_boolean_0)) then
                Z2_ind_V_reg_1039 <= p_Val2_5_fu_505_p2(17 downto 13);
                ap_reg_pp0_iter10_not_demorgan_reg_915 <= ap_reg_pp0_iter9_not_demorgan_reg_915;
                ap_reg_pp0_iter10_p_Result_s_reg_908 <= ap_reg_pp0_iter9_p_Result_s_reg_908;
                ap_reg_pp0_iter10_p_Val2_9_reg_970 <= ap_reg_pp0_iter9_p_Val2_9_reg_970;
                ap_reg_pp0_iter10_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter9_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter10_tmp_25_reg_945 <= ap_reg_pp0_iter9_tmp_25_reg_945;
                ap_reg_pp0_iter10_tmp_26_reg_996 <= ap_reg_pp0_iter9_tmp_26_reg_996;
                ap_reg_pp0_iter10_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter9_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter10_tmp_78_reg_953 <= ap_reg_pp0_iter9_tmp_78_reg_953;
                ap_reg_pp0_iter11_not_demorgan_reg_915 <= ap_reg_pp0_iter10_not_demorgan_reg_915;
                ap_reg_pp0_iter11_p_Result_s_reg_908 <= ap_reg_pp0_iter10_p_Result_s_reg_908;
                ap_reg_pp0_iter11_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter10_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter11_tmp_25_reg_945 <= ap_reg_pp0_iter10_tmp_25_reg_945;
                ap_reg_pp0_iter11_tmp_26_reg_996 <= ap_reg_pp0_iter10_tmp_26_reg_996;
                ap_reg_pp0_iter11_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter10_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter11_tmp_78_reg_953 <= ap_reg_pp0_iter10_tmp_78_reg_953;
                ap_reg_pp0_iter12_m_diff_hi_V_reg_1029 <= m_diff_hi_V_reg_1029;
                ap_reg_pp0_iter12_not_demorgan_reg_915 <= ap_reg_pp0_iter11_not_demorgan_reg_915;
                ap_reg_pp0_iter12_p_Result_s_reg_908 <= ap_reg_pp0_iter11_p_Result_s_reg_908;
                ap_reg_pp0_iter12_p_Val2_15_reg_1034 <= p_Val2_15_reg_1034;
                ap_reg_pp0_iter12_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter11_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter12_tmp_25_reg_945 <= ap_reg_pp0_iter11_tmp_25_reg_945;
                ap_reg_pp0_iter12_tmp_26_reg_996 <= ap_reg_pp0_iter11_tmp_26_reg_996;
                ap_reg_pp0_iter12_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter11_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter12_tmp_78_reg_953 <= ap_reg_pp0_iter11_tmp_78_reg_953;
                ap_reg_pp0_iter13_not_demorgan_reg_915 <= ap_reg_pp0_iter12_not_demorgan_reg_915;
                ap_reg_pp0_iter13_p_Result_s_reg_908 <= ap_reg_pp0_iter12_p_Result_s_reg_908;
                ap_reg_pp0_iter13_p_Val2_15_reg_1034 <= ap_reg_pp0_iter12_p_Val2_15_reg_1034;
                ap_reg_pp0_iter13_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter12_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter13_tmp_25_reg_945 <= ap_reg_pp0_iter12_tmp_25_reg_945;
                ap_reg_pp0_iter13_tmp_26_reg_996 <= ap_reg_pp0_iter12_tmp_26_reg_996;
                ap_reg_pp0_iter13_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter12_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter13_tmp_78_reg_953 <= ap_reg_pp0_iter12_tmp_78_reg_953;
                ap_reg_pp0_iter14_not_demorgan_reg_915 <= ap_reg_pp0_iter13_not_demorgan_reg_915;
                ap_reg_pp0_iter14_p_Result_s_reg_908 <= ap_reg_pp0_iter13_p_Result_s_reg_908;
                ap_reg_pp0_iter14_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter13_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter14_tmp_25_reg_945 <= ap_reg_pp0_iter13_tmp_25_reg_945;
                ap_reg_pp0_iter14_tmp_26_reg_996 <= ap_reg_pp0_iter13_tmp_26_reg_996;
                ap_reg_pp0_iter14_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter13_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter14_tmp_78_reg_953 <= ap_reg_pp0_iter13_tmp_78_reg_953;
                ap_reg_pp0_iter15_not_demorgan_reg_915 <= ap_reg_pp0_iter14_not_demorgan_reg_915;
                ap_reg_pp0_iter15_p_Result_s_reg_908 <= ap_reg_pp0_iter14_p_Result_s_reg_908;
                ap_reg_pp0_iter15_p_Val2_17_reg_1059 <= p_Val2_17_reg_1059;
                ap_reg_pp0_iter15_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter14_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter15_tmp_25_reg_945 <= ap_reg_pp0_iter14_tmp_25_reg_945;
                ap_reg_pp0_iter15_tmp_26_reg_996 <= ap_reg_pp0_iter14_tmp_26_reg_996;
                ap_reg_pp0_iter15_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter14_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter15_tmp_78_reg_953 <= ap_reg_pp0_iter14_tmp_78_reg_953;
                ap_reg_pp0_iter16_not_demorgan_reg_915 <= ap_reg_pp0_iter15_not_demorgan_reg_915;
                ap_reg_pp0_iter16_p_Result_s_reg_908 <= ap_reg_pp0_iter15_p_Result_s_reg_908;
                ap_reg_pp0_iter16_p_Val2_17_reg_1059 <= ap_reg_pp0_iter15_p_Val2_17_reg_1059;
                ap_reg_pp0_iter16_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter15_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter16_tmp_25_reg_945 <= ap_reg_pp0_iter15_tmp_25_reg_945;
                ap_reg_pp0_iter16_tmp_26_reg_996 <= ap_reg_pp0_iter15_tmp_26_reg_996;
                ap_reg_pp0_iter16_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter15_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter16_tmp_78_reg_953 <= ap_reg_pp0_iter15_tmp_78_reg_953;
                ap_reg_pp0_iter17_not_demorgan_reg_915 <= ap_reg_pp0_iter16_not_demorgan_reg_915;
                ap_reg_pp0_iter17_p_Result_s_reg_908 <= ap_reg_pp0_iter16_p_Result_s_reg_908;
                ap_reg_pp0_iter17_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter16_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter17_tmp_25_reg_945 <= ap_reg_pp0_iter16_tmp_25_reg_945;
                ap_reg_pp0_iter17_tmp_26_reg_996 <= ap_reg_pp0_iter16_tmp_26_reg_996;
                ap_reg_pp0_iter17_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter16_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter17_tmp_78_reg_953 <= ap_reg_pp0_iter16_tmp_78_reg_953;
                ap_reg_pp0_iter18_not_demorgan_reg_915 <= ap_reg_pp0_iter17_not_demorgan_reg_915;
                ap_reg_pp0_iter18_p_Result_s_reg_908 <= ap_reg_pp0_iter17_p_Result_s_reg_908;
                ap_reg_pp0_iter18_tmp_25_reg_945 <= ap_reg_pp0_iter17_tmp_25_reg_945;
                ap_reg_pp0_iter18_tmp_26_reg_996 <= ap_reg_pp0_iter17_tmp_26_reg_996;
                ap_reg_pp0_iter18_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter17_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter18_tmp_78_reg_953 <= ap_reg_pp0_iter17_tmp_78_reg_953;
                ap_reg_pp0_iter19_p_Result_s_reg_908 <= ap_reg_pp0_iter18_p_Result_s_reg_908;
                ap_reg_pp0_iter19_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter18_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter19_tmp_78_reg_953 <= ap_reg_pp0_iter18_tmp_78_reg_953;
                ap_reg_pp0_iter2_not_demorgan_reg_915 <= ap_reg_pp0_iter1_not_demorgan_reg_915;
                ap_reg_pp0_iter2_p_Result_s_reg_908 <= ap_reg_pp0_iter1_p_Result_s_reg_908;
                ap_reg_pp0_iter2_p_Val2_9_reg_970 <= p_Val2_9_reg_970;
                ap_reg_pp0_iter2_tmp_25_reg_945 <= ap_reg_pp0_iter1_tmp_25_reg_945;
                ap_reg_pp0_iter2_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter1_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter2_tmp_72_reg_986 <= tmp_72_reg_986;
                ap_reg_pp0_iter2_tmp_78_reg_953 <= ap_reg_pp0_iter1_tmp_78_reg_953;
                ap_reg_pp0_iter3_not_demorgan_reg_915 <= ap_reg_pp0_iter2_not_demorgan_reg_915;
                ap_reg_pp0_iter3_p_Result_s_reg_908 <= ap_reg_pp0_iter2_p_Result_s_reg_908;
                ap_reg_pp0_iter3_p_Val2_9_reg_970 <= ap_reg_pp0_iter2_p_Val2_9_reg_970;
                ap_reg_pp0_iter3_tmp_25_reg_945 <= ap_reg_pp0_iter2_tmp_25_reg_945;
                ap_reg_pp0_iter3_tmp_26_reg_996 <= tmp_26_reg_996;
                ap_reg_pp0_iter3_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter2_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter3_tmp_78_reg_953 <= ap_reg_pp0_iter2_tmp_78_reg_953;
                ap_reg_pp0_iter4_not_demorgan_reg_915 <= ap_reg_pp0_iter3_not_demorgan_reg_915;
                ap_reg_pp0_iter4_p_Result_s_reg_908 <= ap_reg_pp0_iter3_p_Result_s_reg_908;
                ap_reg_pp0_iter4_p_Val2_9_reg_970 <= ap_reg_pp0_iter3_p_Val2_9_reg_970;
                ap_reg_pp0_iter4_tmp_25_reg_945 <= ap_reg_pp0_iter3_tmp_25_reg_945;
                ap_reg_pp0_iter4_tmp_26_reg_996 <= ap_reg_pp0_iter3_tmp_26_reg_996;
                ap_reg_pp0_iter4_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter3_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter4_tmp_78_reg_953 <= ap_reg_pp0_iter3_tmp_78_reg_953;
                ap_reg_pp0_iter5_not_demorgan_reg_915 <= ap_reg_pp0_iter4_not_demorgan_reg_915;
                ap_reg_pp0_iter5_p_Result_s_reg_908 <= ap_reg_pp0_iter4_p_Result_s_reg_908;
                ap_reg_pp0_iter5_p_Val2_9_reg_970 <= ap_reg_pp0_iter4_p_Val2_9_reg_970;
                ap_reg_pp0_iter5_r_exp_V_3_reg_1012 <= r_exp_V_3_reg_1012;
                ap_reg_pp0_iter5_tmp_25_reg_945 <= ap_reg_pp0_iter4_tmp_25_reg_945;
                ap_reg_pp0_iter5_tmp_26_reg_996 <= ap_reg_pp0_iter4_tmp_26_reg_996;
                ap_reg_pp0_iter5_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter4_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter5_tmp_78_reg_953 <= ap_reg_pp0_iter4_tmp_78_reg_953;
                ap_reg_pp0_iter6_not_demorgan_reg_915 <= ap_reg_pp0_iter5_not_demorgan_reg_915;
                ap_reg_pp0_iter6_p_Result_s_reg_908 <= ap_reg_pp0_iter5_p_Result_s_reg_908;
                ap_reg_pp0_iter6_p_Val2_9_reg_970 <= ap_reg_pp0_iter5_p_Val2_9_reg_970;
                ap_reg_pp0_iter6_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter5_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter6_tmp_25_reg_945 <= ap_reg_pp0_iter5_tmp_25_reg_945;
                ap_reg_pp0_iter6_tmp_26_reg_996 <= ap_reg_pp0_iter5_tmp_26_reg_996;
                ap_reg_pp0_iter6_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter5_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter6_tmp_78_reg_953 <= ap_reg_pp0_iter5_tmp_78_reg_953;
                ap_reg_pp0_iter7_not_demorgan_reg_915 <= ap_reg_pp0_iter6_not_demorgan_reg_915;
                ap_reg_pp0_iter7_p_Result_s_reg_908 <= ap_reg_pp0_iter6_p_Result_s_reg_908;
                ap_reg_pp0_iter7_p_Val2_9_reg_970 <= ap_reg_pp0_iter6_p_Val2_9_reg_970;
                ap_reg_pp0_iter7_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter6_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter7_tmp_25_reg_945 <= ap_reg_pp0_iter6_tmp_25_reg_945;
                ap_reg_pp0_iter7_tmp_26_reg_996 <= ap_reg_pp0_iter6_tmp_26_reg_996;
                ap_reg_pp0_iter7_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter6_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter7_tmp_78_reg_953 <= ap_reg_pp0_iter6_tmp_78_reg_953;
                ap_reg_pp0_iter8_not_demorgan_reg_915 <= ap_reg_pp0_iter7_not_demorgan_reg_915;
                ap_reg_pp0_iter8_p_Result_s_reg_908 <= ap_reg_pp0_iter7_p_Result_s_reg_908;
                ap_reg_pp0_iter8_p_Val2_9_reg_970 <= ap_reg_pp0_iter7_p_Val2_9_reg_970;
                ap_reg_pp0_iter8_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter7_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter8_tmp_25_reg_945 <= ap_reg_pp0_iter7_tmp_25_reg_945;
                ap_reg_pp0_iter8_tmp_26_reg_996 <= ap_reg_pp0_iter7_tmp_26_reg_996;
                ap_reg_pp0_iter8_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter7_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter8_tmp_78_reg_953 <= ap_reg_pp0_iter7_tmp_78_reg_953;
                ap_reg_pp0_iter9_not_demorgan_reg_915 <= ap_reg_pp0_iter8_not_demorgan_reg_915;
                ap_reg_pp0_iter9_p_Result_s_reg_908 <= ap_reg_pp0_iter8_p_Result_s_reg_908;
                ap_reg_pp0_iter9_p_Val2_9_reg_970 <= ap_reg_pp0_iter8_p_Val2_9_reg_970;
                ap_reg_pp0_iter9_r_exp_V_3_reg_1012 <= ap_reg_pp0_iter8_r_exp_V_3_reg_1012;
                ap_reg_pp0_iter9_tmp_25_reg_945 <= ap_reg_pp0_iter8_tmp_25_reg_945;
                ap_reg_pp0_iter9_tmp_26_reg_996 <= ap_reg_pp0_iter8_tmp_26_reg_996;
                ap_reg_pp0_iter9_tmp_4_i_i_reg_921 <= ap_reg_pp0_iter8_tmp_4_i_i_reg_921;
                ap_reg_pp0_iter9_tmp_78_reg_953 <= ap_reg_pp0_iter8_tmp_78_reg_953;
                exp_Z1P_m_1_V_reg_1064 <= p_Val2_4_fu_549_p2(18 downto 1);
                m_diff_hi_V_reg_1029 <= p_Val2_5_fu_505_p2(26 downto 18);
                p_Val2_10_reg_1094 <= p_Val2_10_fu_600_p2;
                p_Val2_15_reg_1034 <= p_Val2_15_fu_521_p1;
                p_Val2_16_reg_1054 <= hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
                p_Val2_17_reg_1059 <= hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
                p_Val2_1_reg_1089 <= grp_fu_902_p2;
                p_Val2_6_reg_1084 <= p_Val2_6_fu_584_p2;
                r_exp_V_2_reg_1105 <= r_exp_V_2_fu_619_p3;
                r_exp_V_3_reg_1012 <= r_exp_V_3_fu_464_p3;
                sel_tmp10_reg_1126 <= sel_tmp10_fu_732_p2;
                sel_tmp1_reg_1120 <= sel_tmp1_fu_700_p2;
                tmp35_reg_1132 <= tmp35_fu_766_p2;
                tmp_19_reg_1069 <= hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0(26 downto 9);
                tmp_26_reg_996 <= tmp_26_fu_410_p2;
                    tmp_39_reg_1137(30 downto 0) <= tmp_39_fu_789_p3(30 downto 0);
                tmp_48_reg_1024 <= grp_fu_475_p2(45 downto 10);
                tmp_74_reg_1007 <= tmp_74_fu_426_p1;
                tmp_76_reg_1100 <= p_Val2_10_fu_600_p2(43 downto 43);
                tmp_77_reg_1110 <= r_exp_V_2_fu_619_p3(9 downto 7);
                tmp_79_reg_1115 <= tmp_79_fu_636_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0))) then
                ap_reg_pp0_iter1_isNeg_reg_933 <= isNeg_reg_933;
                ap_reg_pp0_iter1_not_demorgan_reg_915 <= not_demorgan_reg_915;
                ap_reg_pp0_iter1_p_Result_s_reg_908 <= p_Result_s_reg_908;
                ap_reg_pp0_iter1_tmp_25_reg_945 <= tmp_25_reg_945;
                ap_reg_pp0_iter1_tmp_4_i_i_reg_921 <= tmp_4_i_i_reg_921;
                ap_reg_pp0_iter1_tmp_78_reg_953 <= tmp_78_reg_953;
                isNeg_reg_933 <= m_exp_fu_244_p2(8 downto 8);
                not_demorgan_reg_915 <= not_demorgan_fu_222_p2;
                p_Result_s_reg_908 <= p_Val2_s_fu_184_p1(31 downto 31);
                    p_Val2_25_cast1_reg_959(35 downto 4) <= p_Val2_25_cast1_fu_319_p1(35 downto 4);
                p_Val2_8_reg_928 <= p_Val2_8_fu_264_p3;
                p_Val2_9_reg_970 <= p_Val2_9_fu_349_p3;
                sh_assign_1_cast_reg_964 <= sh_assign_1_cast_fu_323_p1;
                sh_assign_1_reg_939 <= sh_assign_1_fu_290_p3;
                tmp_1_reg_975 <= p_Val2_9_fu_349_p3(35 downto 4);
                tmp_25_reg_945 <= tmp_25_fu_298_p2;
                tmp_4_i_i_reg_921 <= tmp_4_i_i_fu_234_p2;
                tmp_72_reg_986 <= p_Val2_9_fu_349_p3(35 downto 35);
                tmp_78_reg_953 <= p_Val2_8_fu_264_p3(24 downto 24);
                tmp_7_reg_981 <= p_Val2_9_fu_349_p3(35 downto 23);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then
                r_V_reg_1001 <= grp_fu_893_p3;
            end if;
        end if;
    end process;
    p_Val2_25_cast1_reg_959(3 downto 0) <= "0000";
    tmp_39_reg_1137(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_start));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_start));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_const_logic_0 = ap_start);
    end process;

        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter20, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_start) and (ap_block_pp0_stage0 = ap_const_boolean_0)) or ((ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter20)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_idle_pp0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13) and (ap_const_logic_0 = ap_enable_reg_pp0_iter14) and (ap_const_logic_0 = ap_enable_reg_pp0_iter15) and (ap_const_logic_0 = ap_enable_reg_pp0_iter16) and (ap_const_logic_0 = ap_enable_reg_pp0_iter17) and (ap_const_logic_0 = ap_enable_reg_pp0_iter18) and (ap_const_logic_0 = ap_enable_reg_pp0_iter19) and (ap_const_logic_0 = ap_enable_reg_pp0_iter20))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to19_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13) and (ap_const_logic_0 = ap_enable_reg_pp0_iter14) and (ap_const_logic_0 = ap_enable_reg_pp0_iter15) and (ap_const_logic_0 = ap_enable_reg_pp0_iter16) and (ap_const_logic_0 = ap_enable_reg_pp0_iter17) and (ap_const_logic_0 = ap_enable_reg_pp0_iter18) and (ap_const_logic_0 = ap_enable_reg_pp0_iter19))) then 
            ap_idle_pp0_0to19 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to19 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_start) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to19)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_idle_pp0_0to19))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        ap_const_lv32_0 when (tmp_43_fu_879_p2(0) = '1') else 
        tmp_42_fu_867_p3;
    grp_fu_475_p0 <= ap_const_lv46_B17217F7D(37 - 1 downto 0);
    grp_fu_893_p0 <= ap_const_lv25_B8A(13 - 1 downto 0);
    grp_fu_902_p0 <= grp_fu_902_p00(18 - 1 downto 0);
    grp_fu_902_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1P_m_1_V_reg_1064),36));
    grp_fu_902_p1 <= grp_fu_902_p10(18 - 1 downto 0);
    grp_fu_902_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_reg_1069),36));
    hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 <= tmp_17_fu_539_p1(9 - 1 downto 0);

    hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13))) then 
            hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_1;
        else 
            hls_exp_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_27_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 <= tmp_i1_fu_535_p1(5 - 1 downto 0);

    hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter12))) then 
            hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_1;
        else 
            hls_exp_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_27_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_fu_645_p2 <= "1" when (signed(tmp_77_reg_1110) > signed(ap_const_lv3_0)) else "0";
    isNeg_fu_272_p3 <= m_exp_fu_244_p2(8 downto 8);
    loc_V_1_fu_206_p1 <= p_Val2_s_fu_184_p1(23 - 1 downto 0);
    loc_V_2_fu_678_p3 <= 
        tmp_29_fu_660_p4 when (tmp_76_reg_1100(0) = '1') else 
        tmp_30_fu_669_p4;
    loc_V_fu_196_p4 <= p_Val2_s_fu_184_p1(30 downto 23);
    m_exp_fu_244_p2 <= std_logic_vector(signed(ap_const_lv9_181) + signed(tmp_i_cast_fu_240_p1));
    not_Result_i4_fu_640_p2 <= (ap_reg_pp0_iter18_p_Result_s_reg_908 xor ap_const_lv1_1);
    not_demorgan_fu_222_p2 <= (tmp_i_i_fu_210_p2 and tmp_1_i_i_fu_216_p2);
    or_cond_fu_650_p2 <= (ap_reg_pp0_iter18_tmp_26_reg_996 or icmp_fu_645_p2);
    out_exp_V_fu_685_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) + unsigned(tmp_79_reg_1115));
    p_Result_5_fu_250_p3 <= (ap_const_lv2_1 & loc_V_1_fu_206_p1);
    p_Result_6_fu_690_p4 <= ((ap_const_lv1_0 & out_exp_V_fu_685_p2) & loc_V_2_fu_678_p3);
    p_Result_s_fu_188_p3 <= p_Val2_s_fu_184_p1(31 downto 31);
    p_Val2_10_fu_600_p2 <= std_logic_vector(unsigned(tmp_21_fu_590_p3) + unsigned(tmp_28_cast_fu_597_p1));
    p_Val2_15_fu_521_p1 <= p_Val2_5_fu_505_p2(18 - 1 downto 0);
    p_Val2_18_fu_312_p3 <= (p_Val2_8_reg_928 & ap_const_lv4_0);
        p_Val2_25_cast1_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_18_fu_312_p3),36));

    p_Val2_4_fu_549_p2 <= std_logic_vector(unsigned(tmp_6_i_fu_543_p1) + unsigned(tmp_7_i_fu_546_p1));
    p_Val2_5_fu_505_p2 <= std_logic_vector(signed(tmp_15_fu_491_p1) - signed(tmp_21_cast_fu_501_p1));
    p_Val2_6_fu_584_p2 <= std_logic_vector(unsigned(ap_const_lv28_4) + unsigned(tmp_20_fu_581_p1));
    p_Val2_7_fu_258_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(p_Result_5_fu_250_p3));
    p_Val2_8_fu_264_p3 <= 
        p_Val2_7_fu_258_p2 when (p_Result_s_fu_188_p3(0) = '1') else 
        p_Result_5_fu_250_p3;
    p_Val2_9_fu_349_p3 <= 
        tmp_5_cast_fu_339_p1 when (isNeg_reg_933(0) = '1') else 
        tmp_6_fu_343_p2;
    p_Val2_s_fu_184_p1 <= x;
    p_s_fu_456_p3 <= 
        tmp_11_fu_429_p4 when (tmp_12_fu_445_p2(0) = '1') else 
        ret_V_2_fu_450_p2;
    r_exp_V_2_fu_619_p3 <= 
        ap_reg_pp0_iter17_r_exp_V_3_reg_1012 when (tmp_76_fu_606_p3(0) = '1') else 
        r_exp_V_fu_614_p2;
    r_exp_V_3_fu_464_p3 <= 
        p_s_fu_456_p3 when (tmp_73_fu_438_p3(0) = '1') else 
        tmp_11_fu_429_p4;
    r_exp_V_fu_614_p2 <= std_logic_vector(signed(ap_const_lv10_3FF) + signed(ap_reg_pp0_iter17_r_exp_V_3_reg_1012));
    ret_V_2_fu_450_p2 <= std_logic_vector(unsigned(ap_const_lv10_1) + unsigned(tmp_11_fu_429_p4));
    sel_tmp10_fu_732_p2 <= (sel_tmp6_fu_716_p2 or sel_tmp9_fu_726_p2);
    sel_tmp11_fu_843_p2 <= (tmp33_fu_838_p2 and sel_tmp4_fu_827_p2);
    sel_tmp12_fu_738_p2 <= (or_cond_fu_650_p2 xor ap_const_lv1_1);
    sel_tmp13_fu_744_p2 <= (ap_reg_pp0_iter18_tmp_25_reg_945 and sel_tmp12_fu_738_p2);
    sel_tmp14_fu_754_p2 <= (sel_tmp44_demorgan_fu_749_p2 xor ap_const_lv1_1);
    sel_tmp15_fu_760_p2 <= (sel_tmp13_fu_744_p2 or sel_tmp14_fu_754_p2);
    sel_tmp16_fu_874_p2 <= (tmp35_reg_1132 or tmp34_fu_849_p2);
    sel_tmp1_fu_700_p2 <= (ap_reg_pp0_iter18_not_demorgan_reg_915 xor ap_const_lv1_1);
    sel_tmp2_fu_711_p2 <= (tmp_fu_705_p2 and ap_reg_pp0_iter18_tmp_4_i_i_reg_921);
    sel_tmp3_fu_816_p2 <= (x_is_ninf_fu_797_p2 xor ap_const_lv1_1);
    sel_tmp44_demorgan_fu_749_p2 <= (ap_reg_pp0_iter18_tmp_25_reg_945 or icmp_fu_645_p2);
    sel_tmp4_fu_827_p2 <= (tmp32_fu_822_p2 and sel_tmp_fu_811_p2);
    sel_tmp5_fu_833_p2 <= (ap_reg_pp0_iter19_tmp_78_reg_953 xor ap_const_lv1_1);
    sel_tmp6_fu_716_p2 <= (ap_reg_pp0_iter18_tmp_25_reg_945 and or_cond_fu_650_p2);
    sel_tmp7_fu_801_p2 <= (x_is_ninf_fu_797_p2 and sel_tmp1_reg_1120);
    sel_tmp8_fu_721_p2 <= (ap_reg_pp0_iter18_tmp_25_reg_945 xor ap_const_lv1_1);
    sel_tmp9_fu_726_p2 <= (icmp_fu_645_p2 and sel_tmp8_fu_721_p2);
    sel_tmp_fu_811_p2 <= (ap_reg_pp0_iter19_p_Result_s_reg_908 or tmp_4_i_i_not_fu_806_p2);
        sh_assign_1_cast_cast_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_assign_1_reg_939),29));

        sh_assign_1_cast_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_assign_1_reg_939),32));

    sh_assign_1_fu_290_p3 <= 
        tmp_8_cast_fu_286_p1 when (isNeg_fu_272_p3(0) = '1') else 
        m_exp_fu_244_p2;
    tmp32_fu_822_p2 <= (sel_tmp1_reg_1120 and sel_tmp3_fu_816_p2);
    tmp33_fu_838_p2 <= (sel_tmp10_reg_1126 and sel_tmp5_fu_833_p2);
    tmp34_fu_849_p2 <= (ap_reg_pp0_iter19_tmp_78_reg_953 and sel_tmp10_reg_1126);
    tmp35_fu_766_p2 <= (tmp_28_fu_655_p2 and sel_tmp15_fu_760_p2);
    tmp_10_fu_415_p3 <= (ap_reg_pp0_iter2_tmp_72_reg_986 & ap_const_lv15_4000);
    tmp_11_fu_429_p4 <= r_V_reg_1001(24 downto 15);
    tmp_12_fu_445_p2 <= "1" when (tmp_74_reg_1007 = ap_const_lv15_0) else "0";
    tmp_14_fu_402_p3 <= (tmp_47_fu_395_p3 & ap_const_lv4_0);
        tmp_15_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_reg_pp0_iter10_p_Val2_9_reg_970),38));

    tmp_16_fu_494_p3 <= (tmp_48_reg_1024 & ap_const_lv1_0);
    tmp_17_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_reg_pp0_iter12_m_diff_hi_V_reg_1029),64));
    tmp_1_i_i_fu_216_p2 <= "0" when (loc_V_1_fu_206_p1 = ap_const_lv23_0) else "1";
    tmp_20_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_reg_pp0_iter16_p_Val2_17_reg_1059),28));
        tmp_21_cast_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_494_p3),38));

    tmp_21_fu_590_p3 <= (p_Val2_6_reg_1084 & ap_const_lv17_0);
    tmp_25_fu_298_p2 <= "1" when (signed(m_exp_fu_244_p2) > signed(ap_const_lv9_0)) else "0";
    tmp_26_fu_410_p2 <= "0" when (tmp_14_fu_402_p3 = p_Val2_25_cast1_reg_959) else "1";
    tmp_28_cast_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_1_reg_1089),45));
    tmp_28_fu_655_p2 <= "1" when (signed(r_exp_V_2_reg_1105) < signed(ap_const_lv10_382)) else "0";
    tmp_29_fu_660_p4 <= p_Val2_10_reg_1094(42 downto 20);
    tmp_2_fu_384_p2 <= std_logic_vector(shift_left(unsigned(tmp_1_reg_975),to_integer(unsigned('0' & sh_assign_1_cast_reg_964(31-1 downto 0)))));
    tmp_30_fu_669_p4 <= p_Val2_10_reg_1094(41 downto 19);
    tmp_36_fu_772_p1 <= p_Result_6_fu_690_p4;
    tmp_37_fu_776_p3 <= 
        ap_const_lv32_7F800000 when (sel_tmp2_fu_711_p2(0) = '1') else 
        ap_const_lv32_7FFFFFFF;
    tmp_38_fu_784_p2 <= (sel_tmp2_fu_711_p2 or ap_reg_pp0_iter18_not_demorgan_reg_915);
    tmp_39_fu_789_p3 <= 
        tmp_37_fu_776_p3 when (tmp_38_fu_784_p2(0) = '1') else 
        tmp_36_fu_772_p1;
    tmp_3_fu_388_p2 <= std_logic_vector(shift_right(signed(tmp_1_reg_975),to_integer(unsigned('0' & sh_assign_1_cast_reg_964(31-1 downto 0)))));
    tmp_3_i_i_fu_228_p2 <= "1" when (loc_V_1_fu_206_p1 = ap_const_lv23_0) else "0";
    tmp_40_fu_853_p3 <= 
        ap_const_lv32_7F800000 when (sel_tmp11_fu_843_p2(0) = '1') else 
        ap_const_lv32_0;
    tmp_41_fu_861_p2 <= (sel_tmp11_fu_843_p2 or sel_tmp7_fu_801_p2);
    tmp_42_fu_867_p3 <= 
        tmp_40_fu_853_p3 when (tmp_41_fu_861_p2(0) = '1') else 
        tmp_39_reg_1137;
    tmp_43_fu_879_p2 <= (sel_tmp16_fu_874_p2 and sel_tmp4_fu_827_p2);
    tmp_47_fu_395_p3 <= 
        tmp_2_fu_384_p2 when (ap_reg_pp0_iter1_isNeg_reg_933(0) = '1') else 
        tmp_3_fu_388_p2;
    tmp_4_i_i_fu_234_p2 <= (tmp_i_i_fu_210_p2 and tmp_3_i_i_fu_228_p2);
    tmp_4_i_i_not_fu_806_p2 <= (ap_reg_pp0_iter19_tmp_4_i_i_reg_921 xor ap_const_lv1_1);
        tmp_5_cast_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_333_p2),36));

    tmp_5_fu_333_p2 <= std_logic_vector(shift_right(signed(p_Val2_18_fu_312_p3),to_integer(unsigned('0' & sh_assign_1_cast_cast_fu_326_p1(29-1 downto 0)))));
    tmp_6_fu_343_p2 <= std_logic_vector(shift_left(unsigned(p_Val2_25_cast1_fu_319_p1),to_integer(unsigned('0' & tmp_9_fu_329_p1(31-1 downto 0)))));
    tmp_6_i_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_reg_pp0_iter13_p_Val2_15_reg_1034),19));
    tmp_73_fu_438_p3 <= r_V_reg_1001(24 downto 24);
    tmp_74_fu_426_p1 <= grp_fu_893_p3(15 - 1 downto 0);
    tmp_76_fu_606_p3 <= p_Val2_10_fu_600_p2(43 downto 43);
    tmp_79_fu_636_p1 <= r_exp_V_2_fu_619_p3(8 - 1 downto 0);
    tmp_7_i_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_16_reg_1054),19));
        tmp_8_cast_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_280_p2),9));

    tmp_8_fu_280_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(loc_V_fu_196_p4));
    tmp_9_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_assign_1_cast_fu_323_p1),36));
    tmp_fu_705_p2 <= (not_Result_i4_fu_640_p2 and sel_tmp1_fu_700_p2);
    tmp_i1_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z2_ind_V_reg_1039),64));
    tmp_i_cast_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loc_V_fu_196_p4),9));
    tmp_i_i_fu_210_p2 <= "1" when (loc_V_fu_196_p4 = ap_const_lv8_FF) else "0";
    x_is_ninf_fu_797_p2 <= (ap_reg_pp0_iter19_tmp_4_i_i_reg_921 and ap_reg_pp0_iter19_p_Result_s_reg_908);
end behav;
