// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xforward_kernel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XForward_kernel_CfgInitialize(XForward_kernel *InstancePtr, XForward_kernel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XForward_kernel_Start(XForward_kernel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL) & 0x80;
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XForward_kernel_IsDone(XForward_kernel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XForward_kernel_IsIdle(XForward_kernel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XForward_kernel_IsReady(XForward_kernel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XForward_kernel_EnableAutoRestart(XForward_kernel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XForward_kernel_DisableAutoRestart(XForward_kernel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_AP_CTRL, 0);
}

void XForward_kernel_Set_src_data(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_SRC_DATA_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_SRC_DATA_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_src_data(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_SRC_DATA_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_SRC_DATA_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_dst_data(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_DST_DATA_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_DST_DATA_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_dst_data(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_DST_DATA_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_DST_DATA_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_w01(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W01_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W01_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_w01(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W01_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W01_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_b1(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B1_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B1_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_b1(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B1_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B1_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_w12(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W12_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W12_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_w12(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W12_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W12_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_b2(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B2_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B2_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_b2(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B2_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B2_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_w23(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W23_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W23_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_w23(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W23_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_W23_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_Set_b3(XForward_kernel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B3_DATA, (u32)(Data));
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B3_DATA + 4, (u32)(Data >> 32));
}

u64 XForward_kernel_Get_b3(XForward_kernel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B3_DATA);
    Data += (u64)XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_B3_DATA + 4) << 32;
    return Data;
}

void XForward_kernel_InterruptGlobalEnable(XForward_kernel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_GIE, 1);
}

void XForward_kernel_InterruptGlobalDisable(XForward_kernel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_GIE, 0);
}

void XForward_kernel_InterruptEnable(XForward_kernel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_IER);
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_IER, Register | Mask);
}

void XForward_kernel_InterruptDisable(XForward_kernel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_IER);
    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_IER, Register & (~Mask));
}

void XForward_kernel_InterruptClear(XForward_kernel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XForward_kernel_WriteReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_ISR, Mask);
}

u32 XForward_kernel_InterruptGetEnabled(XForward_kernel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_IER);
}

u32 XForward_kernel_InterruptGetStatus(XForward_kernel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XForward_kernel_ReadReg(InstancePtr->Control_BaseAddress, XFORWARD_KERNEL_CONTROL_ADDR_ISR);
}

