# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project forward_kernel
set_top forward_kernel
add_files "/home/h-ninomiya/SDAccel_Examples/vision/forward_aligned/src/krnl_forward.cl" -cflags " -I /home/h-ninomiya/SDAccel_Examples/vision/forward_aligned/src"
open_solution solution_OCL_REGION_0
set_part xcku115-flvb2104-2-e
create_clock -period 300MHz -name default
set_clock_uncertainty 0.900000
config_rtl -register_reset
config_interface -m_axi_addr64
config_schedule -relax_ii_for_timing
config_compile -pipeline_loops 64
config_compile -name_max_length 256
csynth_design -skip_cdt
export_design -format ipxact -kernel_drc -sdaccel
close_project
puts "Vivado HLS completed successfully"
exit
