// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XFORWARD_KERNEL_H
#define XFORWARD_KERNEL_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xforward_kernel_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XForward_kernel_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XForward_kernel;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XForward_kernel_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XForward_kernel_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XForward_kernel_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XForward_kernel_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XForward_kernel_Initialize(XForward_kernel *InstancePtr, u16 DeviceId);
XForward_kernel_Config* XForward_kernel_LookupConfig(u16 DeviceId);
int XForward_kernel_CfgInitialize(XForward_kernel *InstancePtr, XForward_kernel_Config *ConfigPtr);
#else
int XForward_kernel_Initialize(XForward_kernel *InstancePtr, const char* InstanceName);
int XForward_kernel_Release(XForward_kernel *InstancePtr);
#endif

void XForward_kernel_Start(XForward_kernel *InstancePtr);
u32 XForward_kernel_IsDone(XForward_kernel *InstancePtr);
u32 XForward_kernel_IsIdle(XForward_kernel *InstancePtr);
u32 XForward_kernel_IsReady(XForward_kernel *InstancePtr);
void XForward_kernel_EnableAutoRestart(XForward_kernel *InstancePtr);
void XForward_kernel_DisableAutoRestart(XForward_kernel *InstancePtr);

void XForward_kernel_Set_src_data(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_src_data(XForward_kernel *InstancePtr);
void XForward_kernel_Set_dst_data(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_dst_data(XForward_kernel *InstancePtr);
void XForward_kernel_Set_w01(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_w01(XForward_kernel *InstancePtr);
void XForward_kernel_Set_b1(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_b1(XForward_kernel *InstancePtr);
void XForward_kernel_Set_w12(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_w12(XForward_kernel *InstancePtr);
void XForward_kernel_Set_b2(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_b2(XForward_kernel *InstancePtr);
void XForward_kernel_Set_w23(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_w23(XForward_kernel *InstancePtr);
void XForward_kernel_Set_b3(XForward_kernel *InstancePtr, u64 Data);
u64 XForward_kernel_Get_b3(XForward_kernel *InstancePtr);

void XForward_kernel_InterruptGlobalEnable(XForward_kernel *InstancePtr);
void XForward_kernel_InterruptGlobalDisable(XForward_kernel *InstancePtr);
void XForward_kernel_InterruptEnable(XForward_kernel *InstancePtr, u32 Mask);
void XForward_kernel_InterruptDisable(XForward_kernel *InstancePtr, u32 Mask);
void XForward_kernel_InterruptClear(XForward_kernel *InstancePtr, u32 Mask);
u32 XForward_kernel_InterruptGetEnabled(XForward_kernel *InstancePtr);
u32 XForward_kernel_InterruptGetStatus(XForward_kernel *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
