all:
	g++ He.c -o He.out -O3 -std=c++11
	g++ He_txt.c -o He_txt.out -O3 -std=c++11
	g++ std0dot01.c -o std0dot01.out -O3 -std=c++11
	g++ read_test.c -o read_test.out -g3 -std=c++11
clean:
	rm He.out
	rm He_txt.out
	rm std0dot01.out
	rm read_test.out
