all:
	gcc random.c -o random.out -lm
	gcc random_uniform.c -o random_uniform.out -lm
	gcc random_uniform_histgram.c -o random_uniform_histgram.out -lm
	gcc random_nolmal.c -o random_nolmal.out -lm
	gcc random_nolmal_histgram.c -o random_nolmal_histgram.out -lm

